Update NewRelicLogForwardingHandler
newrelic/newrelic-python-agent pull request #1038
Opened 2024-01-13 00:58 UTC by TimPansino

# Overview

* Update `NewRelicLogForwardingHandler` API for use without automatic instrumentation.
  * Add attribute support for context data.
  * Add logging metrics if enabled.
  * Allow formatters to be used with `NewRelicLogForwardingHandler`.
    * If a formatter is explicitly supplied, it's run before any processing is done is passed the unmodified log record.
  * Add dict message support.
    * As formatters are run first, formatters can use dicts or other data structures to generate a string that New Relic will ingest, without attempting to treat the record as a dict of context attributes.
    * Formatters that return a dict type instead of a string to `NewRelicLogForwardingHandler` will have the message contents treated as a attributes and processed, allowing flexibility.
    * With no formatter specified, dict messages are treated as attributes and processed.

# Related Github Issue

Related to #731

2024-01-18 20:10 UTC, hmstepanek requested changes
In general this looks good. I pushed up a refactor commit to just simplify some of the code complexity. Please take a look and let me know what you think. It just seemed like there were a lot of nested if-else statements so I tried to reduce those.

I'm thinking while we're in this part of the code we might as well remove the old deprecated NewRelicLogHandler-what do you think?

2024-01-24 19:47 UTC, TimPansino commented on newrelic/api/log.py
> +                application = application_instance(activate=False)
This looks good to me

2024-01-24 19:48 UTC, TimPansino commented
> I'm thinking while we're in this part of the code we might as well remove the old deprecated NewRelicLogHandler-what do you think?

I think we should do a round up of removing deprecated code and do just one major version bump for a whole batch.

2024-01-24 19:52 UTC, hmstepanek approved these changes

2024-01-24 19:53 UTC, merged