NR Control Health Checks
newrelic/newrelic-python-agent pull request #1250
Opened 2024-11-08 01:42 UTC by umaannamalai

_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
Describe the changes present in the pull request

# Related Github Issue
Include a link to the related GitHub issue, if applicable

# Testing
The agent includes a suite of tests which should be used to
verify your changes don't break existing functionality. These tests will run with
Github Actions when a pull request is made. More details on running the tests locally can be found
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst#testing-guidelines),
For most contributions it is strongly recommended to add additional tests which
exercise your changes.

2024-12-07 00:06 UTC, TimPansino requested changes

2024-12-07 00:06 UTC, TimPansino commented on tests/agent_features/test_super_agent_health_check.py
> +    time.sleep(5)
I don't love leaving an intentional race condition in the tests but I don't have a much better solution.

2024-12-07 00:06 UTC, TimPansino commented on tests/agent_features/test_super_agent_health_check.py
> +    assert running_threads[4].name == "NR-Control-Health-Session-Thread"
Why 6? Can we leave a comment here explaining what's being tested exactly?

2024-12-07 00:06 UTC, TimPansino commented on tests/agent_unittests/test_agent_protocol.py
> +                return self.STATUS_CODE, response_data
This thing should probably be moved to `testing_support/` if it's getting reused in 2 different test suites now.

2024-12-07 00:47 UTC, umaannamalai commented on newrelic/config.py
>          raise newrelic.api.exceptions.ConfigurationError(f"Unable to open configuration file {config_file}.")
Good call, this feature was started before we merged the TOML logic in.

2024-12-11 01:02 UTC, umaannamalai commented on tests/agent_features/test_super_agent_health_check.py
> +    assert running_threads[1].name == "NR-Control-Health-Main-Thread"
The two expected threads here that we are asserting on are one health thread as well as one main thread that runs in the agent. For the sake of the test, we only care about ensuring the health thread is running in addition to the main thread. I can add a comment here to clarify what those expected threads are supposed to be.

2024-12-13 19:22 UTC, TimPansino commented on newrelic/core/super_agent_health.py
> +        license_key_error = True if self.status == "License key missing in configuration" or self.status == "Invalid license key (HTTP status code 401)" else False
I don't think we can be comparing the previous status to the current one based on the text of the error message, that's both a slow operation and also incredibly fragile. If anyone updates the messages up above it'll introduce bugs unless they happen to spot that this message is duplicated and used in logic.

Can we store either the `license_key_error = True/False` on `self`, or store the `health_status` enum value on the `self`? I would think the latter would be more useful and general.

2024-12-13 20:08 UTC, TimPansino commented
There were way too many string comparisons and hard coded strings going on in the super agent health file, so I've refactored it somewhat.

I'm looking for it to use integers in every conceivable spot to minimize string comparisons and copies, as well as reduce the risk of a future change introducing bugs because we're comparing status messages that are hard coded in 2 places, rather than using integer codes.

To that end, I've redone the file to use the original integer codes as the enum values, eliminated all cases where we have a string like `NR-APM-003`, and instead construct those when writing out to the file. I removed all hard coded references and replaced them with integers referenced via enum.

I also removed the large block of logic to construct different status messages and modeled it somewhat after the logic used in `newrelic/core/agent_protocol.py` to always attempt to format the string with the passed in values, and rely on string formatting to throw away unused values.

2024-12-13 20:22 UTC, TimPansino commented on tests/agent_features/test_super_agent_health_check.py
> +    assert re.search(r"status_time_unix_nano:\s\d+", contents[3]) is not None
```suggestion
    assert int(re.search(r"status_time_unix_nano: (\d+)", contents[3]).group(1)) > 0
```

2024-12-13 20:22 UTC, TimPansino commented on tests/agent_features/test_super_agent_health_check.py
> +    assert contents[3].startswith("status_time_unix_nano:") is True
```suggestion
    assert int(re.search(r"status_time_unix_nano: (\d+)", contents[3]).group(1)) > 0
```

2024-12-13 20:44 UTC, TimPansino approved these changes

2024-12-17 02:01 UTC, hmstepanek approved these changes
Looks good!

2024-12-18 22:53 UTC, merged