Add custom feature events for sklearn
newrelic/newrelic-python-agent pull request #727
Opened 2022-12-27 19:36 UTC by umaannamalai

2023-01-04 20:04 UTC, hmstepanek requested changes
Overall really nice job on this! This was a lot to do in one PR and for the most part you nailed it!

Had a couple requests here. Additionally it looks like there are some lint issues that need to be fixed:
```
  /github/workspace/newrelic/hooks/component_sklearn.py:18:1: F401 'newrelic.api.application.application_instance' imported but unused
  /github/workspace/newrelic/hooks/component_sklearn.py:22:1: F401 'newrelic.core.config.global_settings' imported but unused
  /github/workspace/tests/mlmodel_sklearn/test_feature_events.py:17:1: F401 'pytest' imported but unused
  /github/workspace/tests/mlmodel_sklearn/test_feature_events.py:19:1: F401 'testing_support.fixtures.validate_custom_event_in_application_stats_engine' imported but unused
```

2023-01-05 00:49 UTC, umaannamalai commented on newrelic/hooks/component_sklearn.py
> +# Copyright 2010 New Relic, Inc.
Oops this shouldn't have been committed! Removing this file.

2023-01-06 21:22 UTC, hmstepanek submitted a review, later dismissed

2023-01-06 21:30 UTC, hmstepanek approved these changes
There were a couple outstanding issues I just committed some quick fixes for. I'm gonna pre-approve this assuming the tests pass. Feel free to merge after that!

2023-01-09 18:43 UTC, merged