Add ml_model function wrapper API
newrelic/newrelic-python-agent pull request #739
Opened 2023-01-11 20:30 UTC by umaannamalai

This PR adds a new API that allows users to pass information about their sklearn models including feature names, model names/ versions, and label names.

2023-01-13 23:17 UTC, hmstepanek reviewed
Just posting this as is based on our discussion.

2023-01-13 23:23 UTC, hmstepanek commented on newrelic/hooks/mlmodel_sklearn.py
> +                    feature_name = column_name_mapping[colname] if colname in column_name_mapping else colname
Just as a reminder. The below is 3 predictions with 2 feature columns.
```
>>> np.array(pd.DataFrame({"col1": [0,1,2], "col2":[3,4,5]}))
array([[0, 3],
       [1, 4],
       [2, 5]])
```
The user may only specify one prediction. In which case I think we could cast this to a 2D array:
```
>>> x = [0,1]
>>> np.array([x])
array([[0, 1]])
```

2023-01-13 23:34 UTC, hmstepanek commented on newrelic/hooks/mlmodel_sklearn.py
> +                    feature_name = column_name_mapping[colname] if colname in column_name_mapping else colname
If it comes in handy at all: [newrelic/hooks/mlmodel_sklearn.py](https://github.com/newrelic/newrelic-python-agent/blob/27ad2976a3459b48c5f4b32812a85823e2d82e6d/newrelic/hooks/mlmodel_sklearn.py) in `_calc_prediction_feature_stats`

2023-01-18 20:10 UTC, hmstepanek requested changes
Looking much better! I had a couple implementation suggestions to simplify things/fix some issues. I also requested a couple more tests.

2023-01-18 20:10 UTC, hmstepanek commented on tests/mlmodel_sklearn/test_ml_model.py
> +
We need a couple tests for the error/warning cases:
* if the feature names don't match the number of feature columns and it's a pandas dataframe
* if the feature names don't match the number of feature columns and it's a np array

2023-01-23 21:38 UTC, umaannamalai commented on tests/mlmodel_sklearn/test_ml_model.py
> +class CustomTestModel(BaseDecisionTree):
Yes, that is true! Is there a way to simplify the __init__?

2023-01-25 00:41 UTC, hmstepanek approved these changes
Looks good! Thanks for bearing with me on this-it's been a lot of back and forth! I'm gonna pre-approve this one. If the args,kwargs thing works for implementing the init, great, if not feel free to merge as is.

2023-01-25 17:27 UTC, merged