Upgrade to Pypy38 for TypedDict
newrelic/newrelic-python-agent pull request #861
Opened 2023-06-29 01:07 UTC by lrafeei

This PR updates the pypy3 version for some framework tests from pypy37 to pypy38.  The frameworks use pypy38 for testing:

- aiohttp
- graphql
- aioredis
- redis

This was driven primarily due to TypedDict not working without typing_extensions.

2023-06-29 17:15 UTC, TimPansino requested changes

2023-06-29 17:15 UTC, TimPansino commented on .github/actions/setup-python-matrix/action.yml
> +    - uses: actions/setup-python@v4
This whole file actually was meant to be deleted but showed back up in a rebase. Can you remove it completely?

2023-06-30 06:09 UTC, umaannamalai approved these changes

2023-06-30 06:13 UTC, merged

2023-06-30 19:32 UTC, TimPansino commented on .github/workflows/tests.yml
> +      image: ghcr.io/newrelic/newrelic-python-agent-ci:sha-b0ffe8bdbb28ba0579377076ad680054da8fbc28
We've still got a dev sha pinned here and it's merged into main now. We'll have to fix that in a different PR.