Remove graphql 2 support & promise support
newrelic/newrelic-python-agent pull request #875
Opened 2023-07-19 21:41 UTC by hmstepanek

# Overview
Remove graphql 2 and promises support.
Merge main into branch.

2023-08-10 18:48 UTC, lrafeei commented on tests/component_djangorestframework/test_application.py
> +    (("Function/django.middleware.common:" "CommonMiddleware" + process_response_method), 1),
Could we fix the concatenated strings?  (I realize this is the end result of the linter doing its thing)

```
    (("Function/django.middleware.common:CommonMiddleware" + process_request_method), 1),
    (("Function/django.contrib.sessions.middleware:SessionMiddleware" + process_request_method), 1),
    (("Function/django.contrib.auth.middleware:AuthenticationMiddleware" + process_request_method), 1),
    (("Function/django.contrib.messages.middleware:MessageMiddleware" + process_request_method), 1),
    (("Function/%s:" % url_module_path + "%s.resolve" % url_resolver_cls), 1),
    (("Function/django.middleware.csrf:CsrfViewMiddleware" + process_view_method), 1),
    (("Function/django.contrib.messages.middleware:MessageMiddleware" + process_response_method), 1),
    (("Function/django.middleware.csrf:CsrfViewMiddleware" + process_response_method), 1),
    (("Function/django.contrib.sessions.middleware:SessionMiddleware" + process_response_method), 1),
    (("Function/django.middleware.common:CommonMiddleware" + process_response_method), 1),
```

2023-08-10 18:58 UTC, lrafeei commented on tests/component_graphqlserver/__init__.py
Since we are removing GraphQL2, Python 2 is no longer supported for GraphQL.   Can we remove this __init__.py file since this is a carry over from Python versions < 3.3?

2023-08-10 19:02 UTC, TimPansino commented
Is this branch based off `develop-graphql-async` or is it based off `main`? It SHOULD be directed at `develop-graphql-async` but there's a million merged commits in here from main.

Do we need to merge main first in a different PR so this isn't quite so gigantic?

2023-08-10 19:55 UTC, lrafeei requested changes

2023-08-10 19:55 UTC, lrafeei commented on tests/framework_ariadne/__init__.py
Similar to the graphqlserver __ init__.py file, can we remove this __ init__.py file since this is a carry over from Python versions < 3.3?

2023-08-10 19:55 UTC, lrafeei commented on tests/component_graphqlserver/__init__.py
Since we are removing GraphQL2, Python 2 is no longer supported for GraphQL. Can we remove this __ init__.py file since this is a carry over from Python versions < 3.3?

2023-08-10 19:55 UTC, lrafeei commented on tests/framework_graphene/__init__.py
Similar to the graphqlserver __ init__.py file, can we remove this __ init__.py file since this is a carry over from Python versions < 3.3?

2023-08-10 19:55 UTC, lrafeei commented on tests/framework_graphql/__init__.py
Similar to the graphqlserver __ init__.py file, can we remove this __ init__.py file since this is a carry over from Python versions < 3.3?

2023-08-10 19:55 UTC, lrafeei commented on tests/framework_graphql/test_application.py
> +        ("Python/Framework/GraphQL/%s" % graphql_version, 1),
Can we use get_package_version() here instead?

2023-08-10 19:55 UTC, lrafeei commented on tests/framework_strawberry/__init__.py
Similar to the graphqlserver __ init__.py file, can we remove this __ init__.py file since this is a carry over from Python versions < 3.3?

2023-08-15 22:34 UTC, lrafeei approved these changes

2023-08-16 23:04 UTC, TimPansino commented on tox.ini
>      python-framework_graphql-{py37,py38,py39,py310,py311,pypy38}-graphql03,
Can we convert `graphql03` to `graphqllatest` now?

2023-08-16 23:05 UTC, TimPansino commented
One thing that might be nice would be to prevent hooks from firing on graphql versions less than 3 with a simple check and return when instrumenting. Not sure if that's entirely possible but might be worth it to avoid crashing older apps that definitely won't work now.

2023-08-22 22:36 UTC, lrafeei approved these changes

2023-08-23 17:09 UTC, merged