Firestore Sync Client Instrumentation
newrelic/newrelic-python-agent pull request #880
Opened 2023-07-26 19:04 UTC by TimPansino

# Overview

* Adds instrumentation for the following classes in Google Cloud Firestore's library.
  * Query
  * AggregationQuery
  * WriteBatch
  * BulkWriteBatch
  * Transaction

2023-07-28 20:14 UTC, hmstepanek requested changes
Looks really good! Just a couple small things.

2023-07-28 21:52 UTC, TimPansino commented on newrelic/hooks/datastore_firestore.py
> +    try:
Yeah that's probably better to collapse all 3

2023-07-28 21:53 UTC, TimPansino commented on tests/datastore_firestore/test_collections.py
> +    documents_stream = [_ for _ in collection.stream()]
It wasn't consuming the iterator on older python versions, it just returned the generator object in a list. That might have been a change in behavior in Python 3.9

2023-07-31 17:38 UTC, hmstepanek approved these changes
Looks good!

2023-07-31 17:38 UTC, merged