Package Version Performance Regression
newrelic/newrelic-python-agent pull request #970
Opened 2023-11-09 23:09 UTC by TimPansino

# Overview

* Fixes performance issues with `get_package_version` by reverting #878.
* Avoid reintroducing DeprecationWarnings by suppressing warnings when accessing package version attributes.
  * Accessing these first for speed is intended behavior whether or not the version attribute is marked as deprecated. The agent is robust enough to handle the removal of these attributes, which makes the DeprecationWarnings irrelevant.

2023-11-11 00:47 UTC, hmstepanek requested changes

2023-11-11 00:47 UTC, hmstepanek commented on tests/agent_unittests/test_package_version_utils.py
>      delattr(pytest, attr)
```suggestion
```

2023-11-11 00:47 UTC, hmstepanek commented on tests/agent_unittests/test_package_version_utils.py
>      delattr(pytest, attr)
```suggestion
```

2023-11-11 00:47 UTC, hmstepanek commented on tests/agent_unittests/test_package_version_utils.py
> +    assert get_package_version("pytest") == "3.2.1"
```suggestion
    assert get_package_version("pytest") == "3.2.1"
    
```

2023-11-13 22:16 UTC, umaannamalai approved these changes

2023-11-13 22:17 UTC, hmstepanek approved these changes

2023-11-13 22:17 UTC, merged