OpenAI and Bedrock Preview
newrelic/newrelic-python-agent pull request #971
Opened 2023-11-10 00:25 UTC by lrafeei

# Overview

- Merges Bedrock and OpenAI branches
- Adds ML metrics for OpenAI and Bedrock

2023-11-10 22:42 UTC, umaannamalai commented
We will hold off on merging this PR to main until the features are GAed.

2023-11-11 01:17 UTC, hmstepanek requested changes

2023-11-11 01:17 UTC, hmstepanek commented on tests/external_botocore/test_bedrock_chat_completion.py
> +            ("Python/ML/Botocore/%s" % BOTOCORE_VERSION, 1),
This should actually be `Python/ML/Bedrock/%s`

2023-11-13 23:45 UTC, hmstepanek approved these changes
Looks good!

2023-11-14 17:49 UTC, umaannamalai approved these changes
🚀

2023-11-14 22:31 UTC, merged