Deprecate ObjectWrapper API
newrelic/newrelic-python-agent pull request #996
Opened 2023-12-06 19:19 UTC by TimPansino

# Overview
## Context 

`ObjectWrapper` was previously used in instrumentation but was simply a custom and more manual version of `FunctionWrapper` from `wrapt`. There is no functional difference in how it is used today in the agent and should be deprecated and removed.

## Changes

* Deprecate `ObjectWrapper` API.
* Add `CallableObjectProxy` to public APIs to replace some of the functionality of `ObjectWrapper`
* Add missing `NewRelicContextFormatter` supportability wrapping in `newrelic.agent`.
* Remove instrumentation references to `ObjectWrapper`, replacing with `FunctionWrapper` or `ObjectProxy`.
* Remove custom `ObjectWrapper` implementation and instead create a pass through to `FunctionWrapper`.

2023-12-22 23:43 UTC, hmstepanek requested changes
In general this looks good. I had one question about the import path change. It looks correct to me but I think we should change all of them or none of them as there are a lot more occurrences than just this one.

2024-01-05 20:29 UTC, TimPansino commented on newrelic/hooks/framework_webpy.py
> +from newrelic.common.object_wrapper import callable_name
I've changed all these references now to point to the new object wrapper location

2024-01-05 21:45 UTC, hmstepanek requested changes
It looks like we are importing callable_name from object_wrappers when it should be importing from object_names. Note the linter caught this issue but the tests did not. One of those rare cases where the linter caught something super important.

2024-01-05 21:45 UTC, hmstepanek commented on newrelic/hooks/framework_pylons.py
> +import newrelic.common.object_wrapper
All of these callable name usages should import from `newrelic.common.object_names`? At this point, callable_name isn't even imported in object_wrapper. The pylint linter caught this issue if you look at the megalinter logs. The tests didn't fail though cause we don't actually have tests for this file.

2024-01-05 21:58 UTC, hmstepanek commented on newrelic/hooks/framework_pylons.py
> +import newrelic.common.object_wrapper
I just pushed up a couple fixes for this.

2024-01-05 22:16 UTC, hmstepanek approved these changes
I think this looks good now. Maybe just have a quick review of the commits I made before merging as a double check?

2024-01-05 23:38 UTC, merged